[server]
logLevel = "info"

[rtsp]
enabled = true
address = ":8554"

[rtmp]
enabled = true
address = ":1935"

[hls]
enabled = true
address = ":8888"
variant = "lowLatency"
segmentCount = 6
segmentDuration = "1s"
partDuration = "200ms"
alwaysRemux = true

[webrtc]
enabled = true
address = ":8889"

[srt]
enabled = true
address = ":8890"

[paths.all]
source = "publisher"
runOnDemand = true
runOnDemandRestart = true
