services:
  - type: web
    name: mediamtx
    env: docker
    plan: free
    repo: https://github.com/Ndutech1/mediamtx.git  # 🔧 FIXED: must be actual repo, not YAML file
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: MTX_CONF
        value: /mediamtx.yml  # 🔧 use absolute path (Render runs root inside container)
    ports:
      - 8889  # ✅ WebRTC HTTP port
