services:
  - type: web
    name: mediamtx
    env: docker
    plan: free
    repo: https://github.com/Ndutech1/mediamtx.git
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: MTX_CONF
        value: /mediamtx.yml
    